// @generated by handbook/bin/gen-related-tools.mjs from handbook/tools.json — DO NOT EDIT.
// To change this tool's related-tools section, edit tools.json (this tool's `related[]`, or the
// referenced tools' hub.icon/hub.card), then run `node handbook/bin/gen-related-tools.mjs format-json`
// (or with no arg to regenerate every active tool) and commit the result.

export interface RelatedToolCard {
  slug: string;
  icon: string;
  name: Record<string, string>;
  desc: Record<string, string>;
}

/** Curated related tools (Issue #177) — same hub.group baseline + genuine cross-group workflow ties. */
export const RELATED_TOOLS: RelatedToolCard[] = [
  {
    "slug": "format-sql",
    "icon": "🗄️",
    "name": {
      "en": "Format SQL",
      "ja": "SQL整形",
      "zh": "格式化 SQL",
      "de": "SQL formatieren",
      "es": "Formatear SQL"
    },
    "desc": {
      "en": "Pretty-print SQL queries across MySQL, PostgreSQL and more dialects.",
      "ja": "MySQL・PostgreSQLなど複数の方言に対応したSQLクエリの整形。",
      "zh": "支持 MySQL、PostgreSQL 等多种方言的 SQL 查询格式化。",
      "de": "SQL-Abfragen für MySQL, PostgreSQL und weitere Dialekte formatieren.",
      "es": "Formatea consultas SQL en MySQL, PostgreSQL y otros dialectos."
    }
  },
  {
    "slug": "compare-text",
    "icon": "⚖️",
    "name": {
      "en": "Compare Text",
      "ja": "テキスト比較",
      "zh": "比较文本",
      "de": "Text vergleichen",
      "es": "Comparar texto"
    },
    "desc": {
      "en": "Diff two texts, line by line.",
      "ja": "2つのテキストを行単位で差分表示。",
      "zh": "逐行比较两段文本的差异。",
      "de": "Vergleiche zwei Texte Zeile für Zeile.",
      "es": "Compara dos textos línea por línea."
    }
  },
  {
    "slug": "xlsx-to-json",
    "icon": "🧾",
    "name": {
      "en": "XLSX to JSON",
      "ja": "XLSX→JSON変換",
      "zh": "XLSX 转 JSON",
      "de": "XLSX zu JSON",
      "es": "XLSX a JSON"
    },
    "desc": {
      "en": "Convert an Excel sheet into JSON or JSONL.",
      "ja": "Excelシートをそれ自体JSON/JSONLに変換。",
      "zh": "将 Excel 工作表转换为 JSON 或 JSONL。",
      "de": "Wandelt ein Excel-Arbeitsblatt in JSON oder JSONL um.",
      "es": "Convierte una hoja de Excel a JSON o JSONL."
    }
  }
];

/** This tool's own engineering-notes article slug (/blog/<slug>/), or null if none is published yet. */
export const BLOG_SLUG: string | null = 'format-json';
